name: Build

on:
  push:
    branches:
      - "*"

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 16
          registry-url: https://npm.pkg.github.com/
          scope: '@gammaswap'
      - run: yarn
        env:
          NODE_AUTH_TOKEN: ${{secrets.GS_TOKEN}}
      - run: tsc --watch false
      - run: yarn build
